version: 2

sources:
  - name: silver
    database: food_delivery
    schema: silver
    tables:
      - name: orders
      - name: order_items
      - name: delivery_status
      - name: restaurant_updates
      - name: customer_actions
